package com


val CityStateData =
    """
  
    [
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "India Gate",
            "Type": "War Memorial",
            "Latitude": 28.6129,
            "Longitude": 77.2295
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Humayun's Tomb",
            "Type": "Tomb",
            "Latitude": 28.5933,
            "Longitude": 77.2507
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Akshardham Temple",
            "Type": "Temple",
            "Latitude": 28.6127,
            "Longitude": 77.2773
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Waste to Wonder Park",
            "Type": "Theme Park",
            "Latitude": 28.5825,
            "Longitude": 77.2906
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Jantar Mantar",
            "Type": "Observatory",
            "Latitude": 28.6271,
            "Longitude": 77.2166
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Chandni Chowk",
            "Type": "Market",
            "Latitude": 28.6562,
            "Longitude": 77.2301
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Lotus Temple",
            "Type": "Temple",
            "Latitude": 28.5535,
            "Longitude": 77.2588
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Red Fort",
            "Type": "Fort",
            "Latitude": 28.6562,
            "Longitude": 77.2410
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Agrasen ki Baoli",
            "Type": "Stepwell",
            "Latitude": 28.6260,
            "Longitude": 77.2249
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Sunder Nursery",
            "Type": "Park",
            "Latitude": 28.5930,
            "Longitude": 77.2433
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Garden of Five Senses",
            "Type": "Park",
            "Latitude": 28.5174,
            "Longitude": 77.1870
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Lodhi Garden",
            "Type": "Park",
            "Latitude": 28.5937,
            "Longitude": 77.2196
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "National Gallery of Modern Art",
            "Type": "Museum",
            "Latitude": 28.6015,
            "Longitude": 77.2333
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "National Zoological Park",
            "Type": "Zoo",
            "Latitude": 28.6080,
            "Longitude": 77.2488
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "Qutub Minar",
            "Type": "Monument",
            "Latitude": 28.5244,
            "Longitude": 77.1855
        },
        {
            "State": "Delhi",
            "City": "Delhi",
            "Name": "National Science Centre",
            "Type": "Science",
            "Latitude": 28.6135,
            "Longitude": 77.2477
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Marine Drive",
            "Type": "Promenade",
            "Latitude": 18.9435,
            "Longitude": 72.8235
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Gateway of India",
            "Type": "Monument",
            "Latitude": 18.9220,
            "Longitude": 72.8347
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya",
            "Type": "Museum",
            "Latitude": 18.9260,
            "Longitude": 72.8326
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Sanjay Gandhi National Park",
            "Type": "National Park",
            "Latitude": 19.2147,
            "Longitude": 72.9106
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Siddhivinayak Temple",
            "Type": "Temple",
            "Latitude": 19.0176,
            "Longitude": 72.8306
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Mahalaxmi Temple",
            "Type": "Temple",
            "Latitude": 18.9822,
            "Longitude": 72.8081
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Haji Ali Dargah",
            "Type": "Religious Shrine",
            "Latitude": 18.9828,
            "Longitude": 72.8080
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Chowpatty Beach",
            "Type": "Beach",
            "Latitude": 18.9543,
            "Longitude": 72.8120
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Essel World",
            "Type": "Amusement Park",
            "Latitude": 19.2364,
            "Longitude": 72.8056
        },
        {
            "State": "Maharashtra",
            "City": "Mumbai",
            "Name": "Elephanta Caves",
            "Type": "Monument",
            "Latitude": 18.9633,
            "Longitude": 72.9316
        },
        {
            "State": "Maharashtra",
            "City": "Lonavala",
            "Name": "Imagicaa",
            "Type": "Amusement Park",
            "Latitude": 18.7586,
            "Longitude": 73.3351
        },
        {
            "State": "Karnataka",
            "City": "Bangalore",
            "Name": "Bangalore Palace",
            "Type": "Palace",
            "Latitude": 12.9985,
            "Longitude": 77.5921
        },
        {
            "State": "Karnataka",
            "City": "Bangalore",
            "Name": "Lalbagh Botanical Garden",
            "Type": "Botanical Garden",
            "Latitude": 12.9507,
            "Longitude": 77.5848
        },
        {
            "State": "Karnataka",
            "City": "Bangalore",
            "Name": "Cubbon Park",
            "Type": "Park",
            "Latitude": 12.9763,
            "Longitude": 77.5929
        },
        {
            "State": "Karnataka",
            "City": "Bangalore",
            "Name": "Vidhana Soudha",
            "Type": "Government Building",
            "Latitude": 12.9796,
            "Longitude": 77.5907
        },
        {
            "State": "Karnataka",
            "City": "Bangalore",
            "Name": "ISKCON Temple Bangalore",
            "Type": "Temple",
            "Latitude": 13.0095,
            "Longitude": 77.5511
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Charminar",
            "Type": "Landmark",
            "Latitude": 17.3616,
            "Longitude": 78.4747
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Golconda Fort",
            "Type": "Fort",
            "Latitude": 17.3833,
            "Longitude": 78.4011
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Hussain Sagar Lake",
            "Type": "Lake",
            "Latitude": 17.4239,
            "Longitude": 78.4738
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Ramoji Film City",
            "Type": "Film Studio",
            "Latitude": 17.2543,
            "Longitude": 78.6808
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Salar Jung Museum",
            "Type": "Museum",
            "Latitude": 17.3714,
            "Longitude": 78.4804
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Qutb Shahi Tombs",
            "Type": "Tombs",
            "Latitude": 17.3853,
            "Longitude": 78.3968
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Birla Mandir",
            "Type": "Temple",
            "Latitude": 17.4062,
            "Longitude": 78.4691
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Chowmahalla Palace",
            "Type": "Palace",
            "Latitude": 17.3578,
            "Longitude": 78.4714
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Nehru Zoological Park",
            "Type": "Zoo",
            "Latitude": 17.3500,
            "Longitude": 78.4510
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Lumbini Park",
            "Type": "Park",
            "Latitude": 17.4156,
            "Longitude": 78.4747
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Victoria Memorial",
            "Type": "Museum",
            "Latitude": 22.5448,
            "Longitude": 88.3426
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Howrah Bridge",
            "Type": "Bridge",
            "Latitude": 22.5850,
            "Longitude": 88.3468
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Indian Museum",
            "Type": "Museum",
            "Latitude": 22.5577,
            "Longitude": 88.3515
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Dakshineswar Kali Temple",
            "Type": "Temple",
            "Latitude": 22.6540,
            "Longitude": 88.3576
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Kalighat Kali Temple",
            "Type": "Temple",
            "Latitude": 22.5235,
            "Longitude": 88.3464
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Eden Gardens",
            "Type": "Cricket Ground",
            "Latitude": 22.5646,
            "Longitude": 88.3433
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Alipore Zoological Gardens",
            "Type": "Zoo",
            "Latitude": 22.5365,
            "Longitude": 88.3310
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Science City Kolkata",
            "Type": "Science",
            "Latitude": 22.5395,
            "Longitude": 88.4072
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Belur Math",
            "Type": "Site",
            "Latitude": 22.6318,
            "Longitude": 88.3550
        },
        {
            "State": "West Bengal",
            "City": "Kolkata",
            "Name": "Marble Palace",
            "Type": "Palace",
            "Latitude": 22.5856,
            "Longitude": 88.3639
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Calangute Beach",
            "Type": "Beach",
            "Latitude": 15.5439,
            "Longitude": 73.7553
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Basilica of Bom Jesus",
            "Type": "Church",
            "Latitude": 15.5009,
            "Longitude": 73.9116
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Fort Aguada",
            "Type": "Fort",
            "Latitude": 15.4925,
            "Longitude": 73.7735
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Dudhsagar Falls",
            "Type": "Waterfall",
            "Latitude": 15.3145,
            "Longitude": 74.3142
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Anjuna Beach",
            "Type": "Beach",
            "Latitude": 15.5753,
            "Longitude": 73.7436
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Chapora Fort",
            "Type": "Fort",
            "Latitude": 15.6048,
            "Longitude": 73.7444
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Se Cathedral",
            "Type": "Church",
            "Latitude": 15.5005,
            "Longitude": 73.9121
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Baga Beach",
            "Type": "Beach",
            "Latitude": 15.5523,
            "Longitude": 73.7517
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Arambol Beach",
            "Type": "Beach",
            "Latitude": 15.6860,
            "Longitude": 73.7045
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Palolem Beach",
            "Type": "Beach",
            "Latitude": 15.0094,
            "Longitude": 74.0234
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Colva Beach",
            "Type": "Beach",
            "Latitude": 15.2793,
            "Longitude": 73.9220
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Miramar Beach",
            "Type": "Beach",
            "Latitude": 15.4745,
            "Longitude": 73.8080
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Aguada Beach",
            "Type": "Beach",
            "Latitude": 15.4925,
            "Longitude": 73.7735
        },
        {
            "State": "Goa",
            "City": "Goa",
            "Name": "Dr. Salim Ali Bird Sanctuary",
            "Type": "Bird Sanctuary",
            "Latitude": 15.5276,
            "Longitude": 73.8669
        },
        {
            "State": "Gujarat",
            "City": "Ahmedabad",
            "Name": "Sabarmati Ashram",
            "Type": "Historical",
            "Latitude": 23.0600,
            "Longitude": 72.5800
        },
        {
            "State": "Gujarat",
            "City": "Dwarka",
            "Name": "Dwarkadhish Temple",
            "Type": "Temple",
            "Latitude": 22.2394,
            "Longitude": 68.9678
        },
        {
            "State": "Gujarat",
            "City": "Junagadh",
            "Name": "Gir National Park",
            "Type": "National Park",
            "Latitude": 21.1240,
            "Longitude": 70.8333
        },
        {
            "State": "Gujarat",
            "City": "Bhuj",
            "Name": "White Desert",
            "Type": "Site",
            "Latitude": 23.7333,
            "Longitude": 70.8333
        },
        {
            "State": "Gujarat",
            "City": "Vadodara",
            "Name": "Laxmi Vilas Palace",
            "Type": "Palace",
            "Latitude": 22.3000,
            "Longitude": 73.2000
        },
        {
            "State": "Gujarat",
            "City": "Somnath",
            "Name": "Somnath Temple",
            "Type": "Temple",
            "Latitude": 20.8880,
            "Longitude": 70.4010
        },
        {
            "State": "Gujarat",
            "City": "Rann of Kutch",
            "Name": "Rann Utsav",
            "Type": "Cultural",
            "Latitude": 23.8333,
            "Longitude": 70.8333
        },
        {
            "State": "Gujarat",
            "City": "Kevadia",
            "Name": "Statue of Unity",
            "Type": "Monument",
            "Latitude": 21.8380,
            "Longitude": 73.7191
        },
        {
            "State": "Gujarat",
            "City": "Gandhinagar",
            "Name": "Dandi Kutir",
            "Type": "Museum",
            "Latitude": 23.2230,
            "Longitude": 72.6500
        },
        {
            "State": "Gujarat",
            "City": "Ahmedabad",
            "Name": "Sabarmati Riverfront",
            "Type": "Urban Development Project",
            "Latitude": 23.0333,
            "Longitude": 72.6167
        },
        {
            "State": "Gujarat",
            "City": "Ahmedabad",
            "Name": "Manek Chowk",
            "Type": "Market",
            "Latitude": 23.0270,
            "Longitude": 72.5830
        },
        {
            "State": "Gujarat",
            "City": "Ahmedabad",
            "Name": "Science City",
            "Type": "Science",
            "Latitude": 23.0902,
            "Longitude": 72.5296
        },
        {
            "State": "Rajasthan",
            "City": "Jaipur",
            "Name": "Hawa Mahal",
            "Type": "Palace",
            "Latitude": 26.9239,
            "Longitude": 75.8267
        },
        {
            "State": "Rajasthan",
            "City": "Udaipur",
            "Name": "City Palace",
            "Type": "Palace",
            "Latitude": 24.5762,
            "Longitude": 73.6835
        },
        {
            "State": "Rajasthan",
            "City": "Jaisalmer",
            "Name": "Jaisalmer Fort",
            "Type": "Fort",
            "Latitude": 26.9124,
            "Longitude": 70.9128
        },
        {
            "State": "Rajasthan",
            "City": "Sawai Madhopur",
            "Name": "Ranthambore National Park",
            "Type": "Wildlife Sanctuary",
            "Latitude": 26.0173,
            "Longitude": 76.5026
        },
        {
            "State": "Rajasthan",
            "City": "Pushkar",
            "Name": "Pushkar Lake",
            "Type": "Temple",
            "Latitude": 26.4881,
            "Longitude": 74.5510
        },
        {
            "State": "Rajasthan",
            "City": "Ajmer",
            "Name": "Ajmer Sharif Dargah",
            "Type": "Shrine",
            "Latitude": 26.4499,
            "Longitude": 74.6399
        },
        {
            "State": "Rajasthan",
            "City": "Jodhpur",
            "Name": "Mehrangarh Fort",
            "Type": "Fort",
            "Latitude": 26.2981,
            "Longitude": 73.0186
        },
        {
            "State": "Rajasthan",
            "City": "Chittorgarh",
            "Name": "Chittorgarh Fort",
            "Type": "Fort",
            "Latitude": 24.8887,
            "Longitude": 74.6484
        },
        {
            "State": "Rajasthan",
            "City": "Mount Abu",
            "Name": "Dilwara Temples",
            "Type": "Temple",
            "Latitude": 24.5925,
            "Longitude": 72.7156
        },
        {
            "State": "Rajasthan",
            "City": "Bikaner",
            "Name": "Junagarh Fort",
            "Type": "Fort",
            "Latitude": 28.0229,
            "Longitude": 73.3171
        },
        {
            "State": "Rajasthan",
            "City": "Jaipur",
            "Name": "Amber Fort",
            "Type": "Fort",
            "Latitude": 26.9855,
            "Longitude": 75.8513
        },
        {
            "State": "Rajasthan",
            "City": "Jaipur",
            "Name": "Jaigarh Fort",
            "Type": "Fort",
            "Latitude": 26.9856,
            "Longitude": 75.8419
        },
        {
            "State": "Rajasthan",
            "City": "Udaipur",
            "Name": "Lake Pichola",
            "Type": "Lake",
            "Latitude": 24.5768,
            "Longitude": 73.6805
        },
        {
            "State": "Punjab",
            "City": "Amritsar",
            "Name": "Golden Temple (Harmandir Sahib)",
            "Type": "Religious Site",
            "Latitude": 31.6200,
            "Longitude": 74.8765
        },
        {
            "State": "Punjab",
            "City": "Amritsar",
            "Name": "Jallianwala Bagh",
            "Type": "Memorial",
            "Latitude": 31.6208,
            "Longitude": 74.8806
        },
        {
            "State": "Punjab",
            "City": "Amritsar",
            "Name": "Wagah Border",
            "Type": "Border Crossing",
            "Latitude": 31.6100,
            "Longitude": 74.5741
        },
        {
            "State": "Punjab",
            "City": "Chandigarh",
            "Name": "Rock Garden",
            "Type": "Sculpture Garden",
            "Latitude": 30.7525,
            "Longitude": 76.8056
        },
        {
            "State": "Kerala",
            "City": "Alappuzha",
            "Name": "Alappuzha Beach",
            "Type": "Beach",
            "Latitude": 9.4968,
            "Longitude": 76.3290
        },
        {
            "State": "Kerala",
            "City": "Munnar",
            "Name": "Munnar Tea Gardens",
            "Type": "Scenic Area",
            "Latitude": 10.0889,
            "Longitude": 77.0595
        },
        {
            "State": "Kerala",
            "City": "Kochi",
            "Name": "Fort Kochi",
            "Type": "Site",
            "Latitude": 9.9656,
            "Longitude": 76.2420
        },
        {
            "State": "Kerala",
            "City": "Thiruvananthapuram",
            "Name": "Padmanabhaswamy Temple",
            "Type": "Temple",
            "Latitude": 8.4821,
            "Longitude": 76.9453
        },
        {
            "State": "Kerala",
            "City": "Kozhikode",
            "Name": "Kozhikode Beach",
            "Type": "Beach",
            "Latitude": 11.2588,
            "Longitude": 75.7754
        },
        {
            "State": "Kerala",
            "City": "Wayanad",
            "Name": "Wayanad Wildlife Sanctuary",
            "Type": "Wildlife Sanctuary",
            "Latitude": 11.7585,
            "Longitude": 76.2133
        },
        {
            "State": "Kerala",
            "City": "Thekkady",
            "Name": "Periyar National Park",
            "Type": "National Park",
            "Latitude": 9.4624,
            "Longitude": 77.2368
        },
        {
            "State": "Kerala",
            "City": "Kumarakom",
            "Name": "Kumarakom Bird Sanctuary",
            "Type": "Bird Sanctuary",
            "Latitude": 9.6172,
            "Longitude": 76.4280
        },
        {
            "State": "Kerala",
            "City": "Varkala",
            "Name": "Varkala Beach",
            "Type": "Beach",
            "Latitude": 8.7350,
            "Longitude": 76.7037
        },
        {
            "State": "Kerala",
            "City": "Bekal",
            "Name": "Bekal Fort",
            "Type": "Fort",
            "Latitude": 12.3938,
            "Longitude": 75.0301
        },
        {
            "State": "Kerala",
            "City": "Kovalam",
            "Name": "Kovalam Beach",
            "Type": "Beach",
            "Latitude": 8.4020,
            "Longitude": 76.9784
        },
        {
            "State": "Kerala",
            "City": "Kannur",
            "Name": "St. Angelo Fort",
            "Type": "Fort",
            "Latitude": 11.8561,
            "Longitude": 75.3810
        },
        {
            "State": "Kerala",
            "City": "Nelliyampathy",
            "Name": "Seethargundu Viewpoint",
            "Type": "Viewpoint",
            "Latitude": 10.5340,
            "Longitude": 76.7053
        },
        {
            "State": "Kerala",
            "City": "Kochi",
            "Name": "Kerala Folklore Museum",
            "Type": "Cultural",
            "Latitude": 9.9231,
            "Longitude": 76.3169
        },
        {
            "State": "Kerala",
            "City": "Kochi",
            "Name": "Wonderla Amusement Park",
            "Type": "Amusement Park",
            "Latitude": 10.9490,
            "Longitude": 76.6294
        },
        {
            "State": "Karnataka",
            "City": "Mysore",
            "Name": "Mysore Palace",
            "Type": "Palace",
            "Latitude": 12.3051,
            "Longitude": 76.6552
        },
        {
            "State": "Karnataka",
            "City": "Hampi",
            "Name": "Hampi Archaeological Ruins",
            "Type": "Site",
            "Latitude": 15.3350,
            "Longitude": 76.4600
        },
        {
            "State": "Karnataka",
            "City": "Coorg",
            "Name": "Abbey Falls",
            "Type": "Waterfall",
            "Latitude": 12.4644,
            "Longitude": 75.7186
        },
        {
            "State": "Karnataka",
            "City": "Gokarna",
            "Name": "Om Beach",
            "Type": "Beach",
            "Latitude": 14.5125,
            "Longitude": 74.3155
        },
        {
            "State": "Karnataka",
            "City": "Chikmagalur",
            "Name": "Mullayanagiri",
            "Type": "Mountain Peak",
            "Latitude": 13.3754,
            "Longitude": 75.7550
        },
        {
            "State": "Karnataka",
            "City": "Badami",
            "Name": "Badami Cave Temples",
            "Type": "Cave",
            "Latitude": 15.9236,
            "Longitude": 75.6852
        },
        {
            "State": "Karnataka",
            "City": "Shivamogga",
            "Name": "Jog Falls",
            "Type": "Waterfall",
            "Latitude": 14.2284,
            "Longitude": 74.7945
        },
        {
            "State": "Karnataka",
            "City": "Mangalore",
            "Name": "Panambur Beach",
            "Type": "Beach",
            "Latitude": 12.9487,
            "Longitude": 74.8120
        },
        {
            "State": "Karnataka",
            "City": "Murudeshwar",
            "Name": "Murudeshwar Temple",
            "Type": "Temple",
            "Latitude": 14.0942,
            "Longitude": 74.4844
        },
        {
            "State": "Karnataka",
            "City": "Bijapur",
            "Name": "Gol Gumbaz",
            "Type": "Mausoleum",
            "Latitude": 16.8305,
            "Longitude": 75.7391
        },
        {
            "State": "Karnataka",
            "City": "Bandipur",
            "Name": "Bandipur National Park",
            "Type": "National Park",
            "Latitude": 11.6683,
            "Longitude": 76.6297
        },
        {
            "State": "Karnataka",
            "City": "Halebidu",
            "Name": "Halebidu Hoysaleswara Temple",
            "Type": "Temple",
            "Latitude": 13.2156,
            "Longitude": 75.9928
        },
        {
            "State": "Maharashtra",
            "City": "Pune",
            "Name": "Shaniwar Wada",
            "Type": "Fort",
            "Latitude": 18.5194,
            "Longitude": 73.8553
        },
        {
            "State": "Maharashtra",
            "City": "Aurangabad",
            "Name": "Ajanta Caves",
            "Type": "Cave",
            "Latitude": 20.5519,
            "Longitude": 75.7033
        },
        {
            "State": "Maharashtra",
            "City": "Nashik",
            "Name": "Sula Vineyards",
            "Type": "Vineyard",
            "Latitude": 20.0055,
            "Longitude": 73.7653
        },
        {
            "State": "Maharashtra",
            "City": "Shirdi",
            "Name": "Sai Baba Temple",
            "Type": "Temple",
            "Latitude": 19.7645,
            "Longitude": 74.4762
        },
        {
            "State": "Maharashtra",
            "City": "Alibaug",
            "Name": "Alibaug Beach",
            "Type": "Beach",
            "Latitude": 18.6422,
            "Longitude": 72.8742
        },
        {
            "State": "Maharashtra",
            "City": "Ratnagiri",
            "Name": "Ganapatipule Temple",
            "Type": "Temple",
            "Latitude": 17.1424,
            "Longitude": 73.2652
        },
        {
            "State": "Maharashtra",
            "City": "Nagpur",
            "Name": "Deekshabhoomi",
            "Type": "Monument",
            "Latitude": 21.1217,
            "Longitude": 79.0747
        },
        {
            "State": "Maharashtra",
            "City": "Kolhapur",
            "Name": "Mahalakshmi Temple",
            "Type": "Temple",
            "Latitude": 16.7033,
            "Longitude": 74.2433
        },
        {
            "State": "Maharashtra",
            "City": "Lonavala",
            "Name": "Karla Caves",
            "Type": "Cave",
            "Latitude": 18.7701,
            "Longitude": 73.4714
        },
        {
            "State": "Maharashtra",
            "City": "Tarkarli",
            "Name": "Tarkarli Beach",
            "Type": "Beach",
            "Latitude": 16.0315,
            "Longitude": 73.4931
        },
        {
            "State": "Maharashtra",
            "City": "Satara",
            "Name": "Kaas Plateau",
            "Type": "Valley",
            "Latitude": 17.7001,
            "Longitude": 73.8142
        },
        {
            "State": "Maharashtra",
            "City": "Matheran",
            "Name": "Echo Point",
            "Type": "Viewpoint",
            "Latitude": 18.9882,
            "Longitude": 73.2715
        },
        {
            "State": "Maharashtra",
            "City": "Ajanta",
            "Name": "Ellora Caves",
            "Type": "Cave",
            "Latitude": 20.0268,
            "Longitude": 75.1786
        },
        {
            "State": "Madhya Pradesh",
            "City": "Khajuraho",
            "Name": "Khajuraho Group of Monuments",
            "Type": "Temples",
            "Latitude": 24.8516,
            "Longitude": 79.9210
        },
        {
            "State": "Madhya Pradesh",
            "City": "Bhopal",
            "Name": "Sanchi Stupa",
            "Type": "Monument",
            "Latitude": 23.4866,
            "Longitude": 77.7391
        },
        {
            "State": "Madhya Pradesh",
            "City": "Indore",
            "Name": "Rajwada Palace",
            "Type": "Palace",
            "Latitude": 22.7177,
            "Longitude": 75.8470
        },
        {
            "State": "Madhya Pradesh",
            "City": "Gwalior",
            "Name": "Gwalior Fort",
            "Type": "Fort",
            "Latitude": 26.2290,
            "Longitude": 78.1734
        },
        {
            "State": "Madhya Pradesh",
            "City": "Ujjain",
            "Name": "Mahakaleshwar Jyotirlinga",
            "Type": "Temple",
            "Latitude": 23.1824,
            "Longitude": 75.7680
        },
        {
            "State": "Madhya Pradesh",
            "City": "Jabalpur",
            "Name": "Dhuandhar Falls",
            "Type": "Waterfall",
            "Latitude": 23.1185,
            "Longitude": 79.8016
        },
        {
            "State": "Madhya Pradesh",
            "City": "Pachmarhi",
            "Name": "Bee Falls",
            "Type": "Waterfall",
            "Latitude": 22.4670,
            "Longitude": 78.4346
        },
        {
            "State": "Madhya Pradesh",
            "City": "Kanha",
            "Name": "Kanha National Park",
            "Type": "Wildlife Sanctuary",
            "Latitude": 22.3345,
            "Longitude": 80.6115
        },
        {
            "State": "Madhya Pradesh",
            "City": "Bandhavgarh",
            "Name": "Bandhavgarh National Park",
            "Type": "National Park",
            "Latitude": 23.6851,
            "Longitude": 81.0014
        },
        {
            "State": "Himachal Pradesh",
            "City": "Shimla",
            "Name": "The Ridge",
            "Type": "Scenic Point",
            "Latitude": 31.1048,
            "Longitude": 77.1734
        },
        {
            "State": "Himachal Pradesh",
            "City": "Manali",
            "Name": "Solang Valley",
            "Type": "Valley",
            "Latitude": 32.3180,
            "Longitude": 77.1580
        },
        {
            "State": "Himachal Pradesh",
            "City": "Dalhousie",
            "Name": "Dalai Lama Temple",
            "Type": "Temple",
            "Latitude": 32.2426,
            "Longitude": 76.3221
        },
        {
            "State": "Himachal Pradesh",
            "City": "Dalhousie",
            "Name": "Khajjiar Lake",
            "Type": "Lake",
            "Latitude": 32.5475,
            "Longitude": 76.0594
        },
        {
            "State": "Himachal Pradesh",
            "City": "Spiti Valley",
            "Name": "Key Monastery",
            "Type": "Monastery",
            "Latitude": 32.2813,
            "Longitude": 78.0081
        },
        {
            "State": "Himachal Pradesh",
            "City": "Kullu",
            "Name": "Great Himalayan National Park",
            "Type": "National Park",
            "Latitude": 31.7619,
            "Longitude": 77.3604
        },
        {
            "State": "Himachal Pradesh",
            "City": "Kangra",
            "Name": "Kangra Fort",
            "Type": "Fort",
            "Latitude": 32.0989,
            "Longitude": 76.2708
        },
        {
            "State": "Himachal Pradesh",
            "City": "Palampur",
            "Name": "Tea Gardens",
            "Type": "Tea Plantation",
            "Latitude": 32.1102,
            "Longitude": 76.5361
        },
        {
            "State": "Himachal Pradesh",
            "City": "Mandi",
            "Name": "Prashar Lake",
            "Type": "Lake",
            "Latitude": 31.7510,
            "Longitude": 77.0837
        },
        {
            "State": "Himachal Pradesh",
            "City": "Bir Billing",
            "Name": "Paragliding Site",
            "Type": "Adventure Sport",
            "Latitude": 32.0456,
            "Longitude": 76.7151
        },
        {
            "State": "Himachal Pradesh",
            "City": "McLeod Ganj",
            "Name": "Triund Trek",
            "Type": "Trekking",
            "Latitude": 32.2426,
            "Longitude": 76.3208
        },
        {
            "State": "Himachal Pradesh",
            "City": "Manikaran",
            "Name": "Manikaran Sahib",
            "Type": "Gurudwara",
            "Latitude": 32.0276,
            "Longitude": 77.3496
        },
        {
            "State": "Himachal Pradesh",
            "City": "Narkanda",
            "Name": "Hatu Peak",
            "Type": "Viewpoint",
            "Latitude": 31.2582,
            "Longitude": 77.4556
        },
        {
            "State": "Himachal Pradesh",
            "City": "Barot",
            "Name": "Barot Valley",
            "Type": "Valley",
            "Latitude": 32.0594,
            "Longitude": 76.8198
        },
        {
            "State": "Himachal Pradesh",
            "City": "Shoja",
            "Name": "Serolsar Lake",
            "Type": "Lake",
            "Latitude": 31.7226,
            "Longitude": 77.4043
        },
        {
            "State": "Himachal Pradesh",
            "City": "Kufri",
            "Name": "Kufri Fun World",
            "Type": "Ski Resort",
            "Latitude": 31.0982,
            "Longitude": 77.2674
        },
        {
            "State": "Uttarakhand",
            "City": "Nainital",
            "Name": "Naini Lake",
            "Type": "Lake",
            "Latitude": 29.3825,
            "Longitude": 79.4636
        },
        {
            "State": "Uttarakhand",
            "City": "Rishikesh",
            "Name": "Laxman Jhula",
            "Type": "Suspension Bridge",
            "Latitude": 30.1221,
            "Longitude": 78.3207
        },
        {
            "State": "Uttarakhand",
            "City": "Haridwar",
            "Name": "Har Ki Pauri",
            "Type": "Ghat",
            "Latitude": 29.9562,
            "Longitude": 78.1710
        },
        {
            "State": "Uttarakhand",
            "City": "Dehradun",
            "Name": "Robber's Cave",
            "Type": "Cave",
            "Latitude": 30.3870,
            "Longitude": 78.0590
        },
        {
            "State": "Uttarakhand",
            "City": "Mussoorie",
            "Name": "Kempty Falls",
            "Type": "Waterfall",
            "Latitude": 30.4401,
            "Longitude": 78.0644
        },
        {
            "State": "Uttarakhand",
            "City": "Auli",
            "Name": "Auli Ski Resort",
            "Type": "Ski Resort",
            "Latitude": 30.5284,
            "Longitude": 79.5657
        },
        {
            "State": "Uttarakhand",
            "City": "Badrinath",
            "Name": "Badrinath Temple",
            "Type": "Temple",
            "Latitude": 30.7433,
            "Longitude": 79.4933
        },
        {
            "State": "Uttarakhand",
            "City": "Almora",
            "Name": "Binsar Wildlife Sanctuary",
            "Type": "Wildlife Sanctuary",
            "Latitude": 29.6730,
            "Longitude": 79.7912
        },
        {
            "State": "Uttarakhand",
            "City": "Ranikhet",
            "Name": "Chaubatia Gardens",
            "Type": "Orchard",
            "Latitude": 29.6254,
            "Longitude": 79.4377
        },
        {
            "State": "Uttarakhand",
            "City": "Jim Corbett",
            "Name": "Jim Corbett National Park",
            "Type": "National Park",
            "Latitude": 29.5300,
            "Longitude": 78.7747
        },
        {
            "State": "Uttarakhand",
            "City": "Uttarkashi",
            "Name": "Gangotri Temple",
            "Type": "Temple",
            "Latitude": 30.9948,
            "Longitude": 78.9372
        },
        {
            "State": "Uttarakhand",
            "City": "Chopta",
            "Name": "Tungnath Temple",
            "Type": "Temple",
            "Latitude": 30.4904,
            "Longitude": 79.2167
        },
        {
            "State": "Uttarakhand",
            "City": "Joshimath",
            "Name": "Valley of Flowers",
            "Type": "National Park",
            "Latitude": 30.7280,
            "Longitude": 79.5981
        },
        {
            "State": "Uttar Pradesh",
            "City": "Agra",
            "Name": "Taj Mahal",
            "Type": "Mausoleum",
            "Latitude": 27.1751,
            "Longitude": 78.0421
        },
        {
            "State": "Uttar Pradesh",
            "City": "Varanasi",
            "Name": "Kashi Vishwanath Temple",
            "Type": "Temple",
            "Latitude": 25.3109,
            "Longitude": 83.0104
        },
        {
            "State": "Uttar Pradesh",
            "City": "Lucknow",
            "Name": "Bara Imambara",
            "Type": "Monument",
            "Latitude": 26.8690,
            "Longitude": 80.9128
        },
        {
            "State": "Uttar Pradesh",
            "City": "Mathura",
            "Name": "Krishna Janmabhoomi",
            "Type": "Temple",
            "Latitude": 27.5035,
            "Longitude": 77.6721
        },
        {
            "State": "Uttar Pradesh",
            "City": "Ayodhya",
            "Name": "Ram Janmabhoomi",
            "Type": "Religious Site",
            "Latitude": 26.7956,
            "Longitude": 82.1940
        },
        {
            "State": "Uttar Pradesh",
            "City": "Vrindavan",
            "Name": "Banke Bihari Temple",
            "Type": "Temple",
            "Latitude": 27.5806,
            "Longitude": 77.6993
        },
        {
            "State": "Uttar Pradesh",
            "City": "Allahabad",
            "Name": "Triveni Sangam",
            "Type": "Confluence",
            "Latitude": 25.4290,
            "Longitude": 81.8750
        },
        {
            "State": "Uttar Pradesh",
            "City": "Jhansi",
            "Name": "Jhansi Fort",
            "Type": "Fort",
            "Latitude": 25.4580,
            "Longitude": 78.5784
        },
        {
            "State": "Uttar Pradesh",
            "City": "Sarnath",
            "Name": "Dhamek Stupa",
            "Type": "Monument",
            "Latitude": 25.3752,
            "Longitude": 83.0228
        },
        {
            "State": "Uttar Pradesh",
            "City": "Fatehpur Sikri",
            "Name": "Buland Darwaza",
            "Type": "Monument",
            "Latitude": 27.0937,
            "Longitude": 77.6613
        },
        {
            "State": "Uttar Pradesh",
            "City": "Noida",
            "Name": "Okhla Bird Sanctuary",
            "Type": "Bird Sanctuary",
            "Latitude": 28.5627,
            "Longitude": 77.3040
        },
        {
            "State": "Uttar Pradesh",
            "City": "Aligarh",
            "Name": "Aligarh Fort",
            "Type": "Fort",
            "Latitude": 27.8850,
            "Longitude": 78.0750
        },
        {
            "State": "Uttar Pradesh",
            "City": "Meerut",
            "Name": "Augarnath Temple",
            "Type": "Temple",
            "Latitude": 28.9845,
            "Longitude": 77.7059
        },
        {
            "State": "Uttar Pradesh",
            "City": "Kanpur",
            "Name": "Allen Forest Zoo",
            "Type": "Zoo",
            "Latitude": 26.4753,
            "Longitude": 80.3052
        },
        {
            "State": "Jammu and Kashmir",
            "City": "Srinagar",
            "Name": "Dal Lake",
            "Type": "Lake",
            "Latitude": 34.1167,
            "Longitude": 74.8667
        },
        {
            "State": "Ladakh",
            "City": "Leh",
            "Name": "Pangong Tso",
            "Type": "Lake",
            "Latitude": 33.7174,
            "Longitude": 78.8914
        },
        {
            "State": "Jammu and Kashmir",
            "City": "Pahalgam",
            "Name": "Betaab Valley",
            "Type": "Valley",
            "Latitude": 34.0167,
            "Longitude": 75.3167
        },
        {
            "State": "Jammu and Kashmir",
            "City": "Jammu",
            "Name": "Vaishno Devi",
            "Type": "Temple",
            "Latitude": 33.0833,
            "Longitude": 75.3167
        },
        {
            "State": "Jammu and Kashmir",
            "City": "Udhampur",
            "Name": "Patnitop Height",
            "Type": "Hill",
            "Latitude": 33.1833,
            "Longitude": 75.3167
        },
        {
            "State": "Jammu and Kashmir",
            "City": "Anantnag",
            "Name": "Amarnath Cave",
            "Type": "Temple",
            "Latitude": 34.0833,
            "Longitude": 75.3167
        },
        {
            "State": "Ladakh",
            "City": "Leh",
            "Name": "Thiksey Monastery",
            "Type": "Monastery",
            "Latitude": 33.4167,
            "Longitude": 77.5667
        },
        {
            "State": "Ladakh",
            "City": "Nubra Valley",
            "Name": "Nubra Valley",
            "Type": "Valley",
            "Latitude": 34.5,
            "Longitude": 77.5
        },
        {
            "State": "Ladakh",
            "City": "Kargil",
            "Name": "Kargil War Memorial",
            "Type": "War Memorial",
            "Latitude": 34.55,
            "Longitude": 76.15
        },
        {
            "State": "Ladakh",
            "City": "Diskit",
            "Name": "Diskit Monastery",
            "Type": "Monastery",
            "Latitude": 34.5,
            "Longitude": 77.3333
        },
        {
            "State": "Jammu and Kashmir",
            "City": "Kishtwar",
            "Name": "Kishtwar National Park",
            "Type": "National Park",
            "Latitude": 33.1667,
            "Longitude": 75.5
        },
        {
            "State": "Ladakh",
            "City": "Hemis",
            "Name": "Hemis National Park",
            "Type": "National Park",
            "Latitude": 33.5,
            "Longitude": 77.5
        },
        {
            "State": "Ladakh",
            "City": "Dras",
            "Name": "Dras War Memorial",
            "Type": "War Memorial",
            "Latitude": 34.5,
            "Longitude": 75.5
        },
        {
            "State": "Ladakh",
            "City": "Leh",
            "Name": "Magnetic Hill",
            "Type": "Gravity Hill",
            "Latitude": 34.5,
            "Longitude": 77.5
        },
        {
            "State": "Ladakh",
            "City": "Leh",
            "Name": "Khardung La Pass",
            "Type": "Hill",
            "Latitude": 35.4167,
            "Longitude": 77.5
        },
        {
            "State": "Ladakh",
            "City": "Leh",
            "Name": "Thiksey Monastery",
            "Type": "Monastery",
            "Latitude": 33.4167,
            "Longitude": 77.5667
        },
        {
            "State": "Daman and Diu",
            "City": "Diu",
            "Name": "Naida Caves",
            "Type": "Cave",
            "Latitude": 20.7120,
            "Longitude": 70.9733
        },
        {
            "State": "Daman and Diu",
            "City": "Diu",
            "Name": "Diu Fort",
            "Type": "Fort",
            "Latitude": 20.7104,
            "Longitude": 70.9722
        },
        {
            "State": "Jharkhand",
            "City": "Deoghar",
            "Name": "Baba Baidyanath Temple",
            "Type": "Temple",
            "Latitude": 24.4652,
            "Longitude": 86.4523
        },
        {
            "State": "Jharkhand",
            "City": "Ranchi",
            "Name": "Pahari Mandir",
            "Type": "Temple",
            "Latitude": 23.3442,
            "Longitude": 85.3368
        },
        {
            "State": "Bihar",
            "City": "Bodh Gaya",
            "Name": "Mahabodhi Temple",
            "Type": "Temple",
            "Latitude": 24.6957,
            "Longitude": 84.9934
        },
        {
            "State": "Bihar",
            "City": "Patna",
            "Name": "Sanjay Gandhi Biological Park",
            "Type": "Zoo",
            "Latitude": 25.6125,
            "Longitude": 85.0780
        },
        {
            "State": "Bihar",
            "City": "Patna",
            "Name": "Takhat Shri Harimandir Ji Patna Sahib",
            "Type": "Gurudwara",
            "Latitude": 25.6242,
            "Longitude": 85.1330
        },
        {
            "State": "Bihar",
            "City": "Patna",
            "Name": "Budhha Smriti Park",
            "Type": "Park",
            "Latitude": 25.6083,
            "Longitude": 85.1350
        },
        {
            "State": "Haryana",
            "City": "Gurugram",
            "Name": "Kingdom of Dreams",
            "Type": "Entertainment",
            "Latitude": 28.4520,
            "Longitude": 77.0707
        },
        {
            "State": "Haryana",
            "City": "Gurugram",
            "Name": "Ambience Mall",
            "Type": "Mall",
            "Latitude": 28.4742,
            "Longitude": 77.0916
        },
        {
            "State": "Haryana",
            "City": "Gurugram",
            "Name": "DLF CyberHub",
            "Type": "Commercial Complex",
            "Latitude": 28.4799,
            "Longitude": 77.0989
        },
        {
            "State": "Delhi",
            "City": "New Delhi",
            "Name": "Gurudwara Bangla Sahib",
            "Type": "Gurudwara",
            "Latitude": 28.6305,
            "Longitude": 77.2167
        },
        {
            "State": "Uttarakhand",
            "City": "Kedarnath",
            "Name": "Kedarnath",
            "Type": "Temple",
            "Latitude": 30.7333,
            "Longitude": 79.0667
        },
        {
            "State": "Uttar Pradesh",
            "City": "Noida",
            "Name": "DLF Mall of India",
            "Type": "Mall",
            "Latitude": 28.5740,
            "Longitude": 77.3197
        },
        {
            "State": "Uttar Pradesh",
            "City": "Greater Noida",
            "Name": "The Grand Venice Mall",
            "Type": "Mall",
            "Latitude": 28.4078,
            "Longitude": 77.5865
        },
        {
            "State": "Karnataka",
            "City": "Bengaluru",
            "Name": "Wonderla Amusement Park",
            "Type": "Amusement Park",
            "Latitude": 12.9770,
            "Longitude": 77.6149
        },
        {
            "State": "Odisha",
            "City": "Bhubaneswar",
            "Name": "Nandankanan Zoological Park",
            "Type": "Zoo",
            "Latitude": 20.3258,
            "Longitude": 85.8231
        },
        {
            "State": "Karnataka",
            "City": "Bengaluru",
            "Name": "Orion Mall",
            "Type": "Mall",
            "Latitude": 13.0114,
            "Longitude": 77.5500
        },
        {
            "State": "Telangana",
            "City": "Hyderabad",
            "Name": "Inorbit Mall Cyberabad",
            "Type": "Mall",
            "Latitude": 17.4430,
            "Longitude": 78.3866
        },
        {
            "State": "Delhi",
            "City": "New Delhi",
            "Name": "Jama Masjid",
            "Type": "Mosque",
            "Latitude": 28.6507,
            "Longitude": 77.2334
        },
        {
            "State": "Tamil Nadu",
            "City": "Rameswaram",
            "Name": "Ramanathaswamy Temple",
            "Type": "Temple",
            "Latitude": 9.2892,
            "Longitude": 79.3131
        },
        {
            "State": "Uttar Pradesh",
            "City": "Greater Noida",
            "Name": "Buddh International Circuit",
            "Type": "Race Track",
            "Latitude": 28.5292,
            "Longitude": 77.5390
        },
        {
            "State": "Uttar Pradesh",
            "City": "Lucknow",
            "Name": "Phoenix Palassio",
            "Type": "Mall",
            "Latitude": 26.8467,
            "Longitude": 80.9736
        },
        {
            "State": "Kerala",
            "City": "Kochi",
            "Name": "LuLu International Shopping Mall",
            "Type": "Mall",
            "Latitude": 10.0049,
            "Longitude": 76.3537
        },
        {
            "State": "Delhi",
            "City": "New Delhi",
            "Name": "Rail Museum",
            "Type": "Museum",
            "Latitude": 28.6347,
            "Longitude": 77.2074
        },
        {
            "State": "Meghalaya",
            "City": "Cherrapunji",
            "Name": "Living Root Bridge",
            "Type": "Natural Feature",
            "Latitude": 25.2978,
            "Longitude": 91.5824
        },
        {
            "State": "Gujarat",
            "City": "Gandhinagar",
            "Name": "Akshardham",
            "Type": "Temple",
            "Latitude": 23.2396,
            "Longitude": 72.6330
        },
        {
            "State": "Uttar Pradesh",
            "City": "Agra",
            "Name": "Agra Fort",
            "Type": "Fort",
            "Latitude": 27.1789,
            "Longitude": 78.0158
        },
        {
            "State": "Madhya Pradesh",
            "City": "Bhopal",
            "Name": "Madhya Pradesh Tribal Museum",
            "Type": "Museum",
            "Latitude": 23.2512,
            "Longitude": 77.4107
        },
        {
            "State": "Rajasthan",
            "City": "Jaipur",
            "Name": "City Palace",
            "Type": "Palace",
            "Latitude": 26.9253,
            "Longitude": 75.8228
        },
        {
            "State": "Rajasthan",
            "City": "Jaipur",
            "Name": "Albert Hall Museum",
            "Type": "Museum",
            "Latitude": 26.9240,
            "Longitude": 75.8183
        }
    ]
  
""".trimIndent()


val Data =
    """
        {
          "AndamanandNicobarIslands": [
            "Port Blair"
          ],
          "Haryana": [
            "Faridabad",
            "Gurgaon",
            "Hisar",
            "Rohtak",
            "Panipat",
            "Karnal",
            "Sonipat",
            "Yamunanagar",
            "Panchkula",
            "Bhiwani",
            "Bahadurgarh",
            "Jind",
            "Sirsa",
            "Thanesar",
            "Kaithal",
            "Palwal",
            "Rewari",
            "Hansi",
            "Narnaul",
            "Fatehabad",
            "Gohana",
            "Tohana",
            "Narwana",
            "Mandi Dabwali",
            "Charkhi Dadri",
            "Shahbad",
            "Pehowa",
            "Samalkha",
            "Pinjore",
            "Ladwa",
            "Sohna",
            "Safidon",
            "Taraori",
            "Mahendragarh",
            "Ratia",
            "Rania",
            "Sarsod"
          ],
          "TamilNadu": [
            "Chennai",
            "Coimbatore",
            "Madurai",
            "Tiruchirappalli",
            "Salem",
            "Tirunelveli",
            "Tiruppur",
            "Ranipet",
            "Nagercoil",
            "Thanjavur",
            "Vellore",
            "Kancheepuram",
            "Erode",
            "Tiruvannamalai",
            "Pollachi",
            "Rajapalayam",
            "Sivakasi",
            "Pudukkottai",
            "Neyveli (TS)",
            "Nagapattinam",
            "Viluppuram",
            "Tiruchengode",
            "Vaniyambadi",
            "Theni Allinagaram",
            "Udhagamandalam",
            "Aruppukkottai",
            "Paramakudi",
            "Arakkonam",
            "Virudhachalam",
            "Srivilliputhur",
            "Tindivanam",
            "Virudhunagar",
            "Karur",
            "Valparai",
            "Sankarankovil",
            "Tenkasi",
            "Palani",
            "Pattukkottai",
            "Tirupathur",
            "Ramanathapuram",
            "Udumalaipettai",
            "Gobichettipalayam",
            "Thiruvarur",
            "Thiruvallur",
            "Panruti",
            "Namakkal",
            "Thirumangalam",
            "Vikramasingapuram",
            "Nellikuppam",
            "Rasipuram",
            "Tiruttani",
            "Nandivaram-Guduvancheri",
            "Periyakulam",
            "Pernampattu",
            "Vellakoil",
            "Sivaganga",
            "Vadalur",
            "Rameshwaram",
            "Tiruvethipuram",
            "Perambalur",
            "Usilampatti",
            "Vedaranyam",
            "Sathyamangalam",
            "Puliyankudi",
            "Nanjikottai",
            "Thuraiyur",
            "Sirkali",
            "Tiruchendur",
            "Periyasemur",
            "Sattur",
            "Vandavasi",
            "Tharamangalam",
            "Tirukkoyilur",
            "Oddanchatram",
            "Palladam",
            "Vadakkuvalliyur",
            "Tirukalukundram",
            "Uthamapalayam",
            "Surandai",
            "Sankari",
            "Shenkottai",
            "Vadipatti",
            "Sholingur",
            "Tirupathur",
            "Manachanallur",
            "Viswanatham",
            "Polur",
            "Panagudi",
            "Uthiramerur",
            "Thiruthuraipoondi",
            "Pallapatti",
            "Ponneri",
            "Lalgudi",
            "Natham",
            "Unnamalaikadai",
            "P.N.Patti",
            "Tharangambadi",
            "Tittakudi",
            "Pacode",
            "O' Valley",
            "Suriyampalayam",
            "Sholavandan",
            "Thammampatti",
            "Namagiripettai",
            "Peravurani",
            "Parangipettai",
            "Pudupattinam",
            "Pallikonda",
            "Sivagiri",
            "Punjaipugalur",
            "Padmanabhapuram",
            "Thirupuvanam"
          ],
          "MadhyaPradesh": [
            "Indore",
            "Bhopal",
            "Jabalpur",
            "Gwalior",
            "Ujjain",
            "Sagar",
            "Ratlam",
            "Satna",
            "Murwara (Katni)",
            "Morena",
            "Singrauli",
            "Rewa",
            "Vidisha",
            "Ganjbasoda",
            "Shivpuri",
            "Mandsaur",
            "Neemuch",
            "Nagda",
            "Itarsi",
            "Sarni",
            "Sehore",
            "Mhow Cantonment",
            "Seoni",
            "Balaghat",
            "Ashok Nagar",
            "Tikamgarh",
            "Shahdol",
            "Pithampur",
            "Alirajpur",
            "Mandla",
            "Sheopur",
            "Shajapur",
            "Panna",
            "Raghogarh-Vijaypur",
            "Sendhwa",
            "Sidhi",
            "Pipariya",
            "Shujalpur",
            "Sironj",
            "Pandhurna",
            "Nowgong",
            "Mandideep",
            "Sihora",
            "Raisen",
            "Lahar",
            "Maihar",
            "Sanawad",
            "Sabalgarh",
            "Umaria",
            "Porsa",
            "Narsinghgarh",
            "Malaj Khand",
            "Sarangpur",
            "Mundi",
            "Nepanagar",
            "Pasan",
            "Mahidpur",
            "Seoni-Malwa",
            "Rehli",
            "Manawar",
            "Rahatgarh",
            "Panagar",
            "Wara Seoni",
            "Tarana",
            "Sausar",
            "Rajgarh",
            "Niwari",
            "Mauganj",
            "Manasa",
            "Nainpur",
            "Prithvipur",
            "Sohagpur",
            "Nowrozabad (Khodargama)",
            "Shamgarh",
            "Maharajpur",
            "Multai",
            "Pali",
            "Pachore",
            "Rau",
            "Mhowgaon",
            "Vijaypur",
            "Narsinghgarh"
          ],
          "Jharkhand": [
            "Dhanbad",
            "Ranchi",
            "Jamshedpur",
            "Bokaro Steel City",
            "Deoghar",
            "Phusro",
            "Adityapur",
            "Hazaribag",
            "Giridih",
            "Ramgarh",
            "Jhumri Tilaiya",
            "Saunda",
            "Sahibganj",
            "Medininagar (Daltonganj)",
            "Chaibasa",
            "Chatra",
            "Gumia",
            "Dumka",
            "Madhupur",
            "Chirkunda",
            "Pakaur",
            "Simdega",
            "Musabani",
            "Mihijam",
            "Patratu",
            "Lohardaga",
            "Tenu dam-cum-Kathhara"
          ],
          "Mizoram": [
            "Aizawl",
            "Lunglei",
            "Saiha"
          ],
          "Nagaland": [
            "Dimapur",
            "Kohima",
            "Zunheboto",
            "Tuensang",
            "Wokha",
            "Mokokchung"
          ],
          "HimachalPradesh": [
            "Shimla",
            "Mandi",
            "Solan",
            "Nahan",
            "Sundarnagar",
            "Palampur",
            "Kullu"
          ],
          "Tripura": [
            "Agartala",
            "Udaipur",
            "Dharmanagar",
            "Pratapgarh",
            "Kailasahar",
            "Belonia",
            "Khowai"
          ],
          "AndhraPradesh": [
            "Visakhapatnam",
            "Vijayawada",
            "Guntur",
            "Nellore",
            "Kurnool",
            "Rajahmundry",
            "Kakinada",
            "Tirupati",
            "Anantapur",
            "Kadapa",
            "Vizianagaram",
            "Eluru",
            "Ongole",
            "Nandyal",
            "Machilipatnam",
            "Adoni",
            "Tenali",
            "Chittoor",
            "Hindupur",
            "Proddatur",
            "Bhimavaram",
            "Madanapalle",
            "Guntakal",
            "Dharmavaram",
            "Gudivada",
            "Srikakulam",
            "Narasaraopet",
            "Rajampet",
            "Tadpatri",
            "Tadepalligudem",
            "Chilakaluripet",
            "Yemmiganur",
            "Kadiri",
            "Chirala",
            "Anakapalle",
            "Kavali",
            "Palacole",
            "Sullurpeta",
            "Tanuku",
            "Rayachoti",
            "Srikalahasti",
            "Bapatla",
            "Naidupet",
            "Nagari",
            "Gudur",
            "Vinukonda",
            "Narasapuram",
            "Nuzvid",
            "Markapur",
            "Ponnur",
            "Kandukur",
            "Bobbili",
            "Rayadurg",
            "Samalkot",
            "Jaggaiahpet",
            "Tuni",
            "Amalapuram",
            "Bheemunipatnam",
            "Venkatagiri",
            "Sattenapalle",
            "Pithapuram",
            "Palasa Kasibugga",
            "Parvathipuram",
            "Macherla",
            "Gooty",
            "Salur",
            "Mandapeta",
            "Jammalamadugu",
            "Peddapuram",
            "Punganur",
            "Nidadavole",
            "Repalle",
            "Ramachandrapuram",
            "Kovvur",
            "Tiruvuru",
            "Uravakonda",
            "Narsipatnam",
            "Yerraguntla",
            "Pedana",
            "Puttur",
            "Renigunta",
            "Rajam",
            "Srisailam Project (Right Flank Colony) Township"
          ],
          "Punjab": [
            "Ludhiana",
            "Patiala",
            "Amritsar",
            "Jalandhar",
            "Bathinda",
            "Pathankot",
            "Hoshiarpur",
            "Batala",
            "Moga",
            "Malerkotla",
            "Khanna",
            "Mohali",
            "Barnala",
            "Firozpur",
            "Phagwara",
            "Kapurthala",
            "Zirakpur",
            "Kot Kapura",
            "Faridkot",
            "Muktsar",
            "Rajpura",
            "Sangrur",
            "Fazilka",
            "Gurdaspur",
            "Kharar",
            "Gobindgarh",
            "Mansa",
            "Malout",
            "Nabha",
            "Tarn Taran",
            "Jagraon",
            "Sunam",
            "Dhuri",
            "Firozpur Cantt.",
            "Sirhind Fatehgarh Sahib",
            "Rupnagar",
            "Jalandhar Cantt.",
            "Samana",
            "Nawanshahr",
            "Rampura Phul",
            "Nangal",
            "Nakodar",
            "Zira",
            "Patti",
            "Raikot",
            "Longowal",
            "Urmar Tanda",
            "Morinda, India",
            "Phillaur",
            "Pattran",
            "Qadian",
            "Sujanpur",
            "Mukerian",
            "Talwara"
          ],
          "Chandigarh": [
            "Chandigarh"
          ],
          "Rajasthan": [
            "Jaipur",
            "Jodhpur",
            "Bikaner",
            "Udaipur",
            "Ajmer",
            "Bhilwara",
            "Alwar",
            "Bharatpur",
            "Pali",
            "Barmer",
            "Sikar",
            "Tonk",
            "Sadulpur",
            "Sawai Madhopur",
            "Nagaur",
            "Makrana",
            "Sujangarh",
            "Sardarshahar",
            "Ladnu",
            "Ratangarh",
            "Nokha",
            "Nimbahera",
            "Suratgarh",
            "Rajsamand",
            "Lachhmangarh",
            "Rajgarh (Churu)",
            "Nasirabad",
            "Nohar",
            "Phalodi",
            "Nathdwara",
            "Pilani",
            "Merta City",
            "Sojat",
            "Neem-Ka-Thana",
            "Sirohi",
            "Pratapgarh",
            "Rawatbhata",
            "Sangaria",
            "Lalsot",
            "Pilibanga",
            "Pipar City",
            "Taranagar",
            "Vijainagar, Ajmer",
            "Sumerpur",
            "Sagwara",
            "Ramganj Mandi",
            "Lakheri",
            "Udaipurwati",
            "Losal",
            "Sri Madhopur",
            "Ramngarh",
            "Rawatsar",
            "Rajakhera",
            "Shahpura",
            "Shahpura",
            "Raisinghnagar",
            "Malpura",
            "Nadbai",
            "Sanchore",
            "Nagar",
            "Rajgarh (Alwar)",
            "Sheoganj",
            "Sadri",
            "Todaraisingh",
            "Todabhim",
            "Reengus",
            "Rajaldesar",
            "Sadulshahar",
            "Sambhar",
            "Prantij",
            "Mount Abu",
            "Mangrol",
            "Phulera",
            "Mandawa",
            "Pindwara",
            "Mandalgarh",
            "Takhatgarh"
          ],
          "Assam": [
            "Guwahati",
            "Silchar",
            "Dibrugarh",
            "Nagaon",
            "Tinsukia",
            "Jorhat",
            "Bongaigaon City",
            "Dhubri",
            "Diphu",
            "North Lakhimpur",
            "Tezpur",
            "Karimganj",
            "Sibsagar",
            "Goalpara",
            "Barpeta",
            "Lanka",
            "Lumding",
            "Mankachar",
            "Nalbari",
            "Rangia",
            "Margherita",
            "Mangaldoi",
            "Silapathar",
            "Mariani",
            "Marigaon"
          ],
          "Odisha": [
            "Bhubaneswar",
            "Cuttack",
            "Raurkela",
            "Brahmapur",
            "Sambalpur",
            "Puri",
            "Baleshwar Town",
            "Baripada Town",
            "Bhadrak",
            "Balangir",
            "Jharsuguda",
            "Bargarh",
            "Paradip",
            "Bhawanipatna",
            "Dhenkanal",
            "Barbil",
            "Kendujhar",
            "Sunabeda",
            "Rayagada",
            "Jatani",
            "Byasanagar",
            "Kendrapara",
            "Rajagangapur",
            "Parlakhemundi",
            "Talcher",
            "Sundargarh",
            "Phulabani",
            "Pattamundai",
            "Titlagarh",
            "Nabarangapur",
            "Soro",
            "Malkangiri",
            "Rairangpur",
            "Tarbha"
          ],
          "Chhattisgarh": [
            "Raipur",
            "Bhilai Nagar",
            "Korba",
            "Bilaspur",
            "Durg",
            "Rajnandgaon",
            "Jagdalpur",
            "Raigarh",
            "Ambikapur",
            "Mahasamund",
            "Dhamtari",
            "Chirmiri",
            "Bhatapara",
            "Dalli-Rajhara",
            "Naila Janjgir",
            "Tilda Newra",
            "Mungeli",
            "Manendragarh",
            "Sakti"
          ],
          "JammuandKashmir": [
            "Srinagar",
            "Jammu",
            "Baramula",
            "Anantnag",
            "Sopore",
            "KathUrban Agglomeration",
            "Rajauri",
            "Punch",
            "Udhampur"
          ],
          "Karnataka": [
            "Bengaluru",
            "Hubli-Dharwad",
            "Belagavi",
            "Mangaluru",
            "Davanagere",
            "Ballari",
            "Mysore",
            "Tumkur",
            "Shivamogga",
            "Raayachuru",
            "Robertson Pet",
            "Kolar",
            "Mandya",
            "Udupi",
            "Chikkamagaluru",
            "Karwar",
            "Ranebennuru",
            "Ranibennur",
            "Ramanagaram",
            "Gokak",
            "Yadgir",
            "Rabkavi Banhatti",
            "Shahabad",
            "Sirsi",
            "Sindhnur",
            "Tiptur",
            "Arsikere",
            "Nanjangud",
            "Sagara",
            "Sira",
            "Puttur",
            "Athni",
            "Mulbagal",
            "Surapura",
            "Siruguppa",
            "Mudhol",
            "Sidlaghatta",
            "Shahpur",
            "Saundatti-Yellamma",
            "Wadi",
            "Manvi",
            "Nelamangala",
            "Lakshmeshwar",
            "Ramdurg",
            "Nargund",
            "Tarikere",
            "Malavalli",
            "Savanur",
            "Lingsugur",
            "Vijayapura",
            "Sankeshwara",
            "Madikeri",
            "Talikota",
            "Sedam",
            "Shikaripur",
            "Mahalingapura",
            "Mudalagi",
            "Muddebihal",
            "Pavagada",
            "Malur",
            "Sindhagi",
            "Sanduru",
            "Afzalpur",
            "Maddur",
            "Madhugiri",
            "Tekkalakote",
            "Terdal",
            "Mudabidri",
            "Magadi",
            "Navalgund",
            "Shiggaon",
            "Shrirangapattana",
            "Sindagi",
            "Sakaleshapura",
            "Srinivaspur",
            "Ron",
            "Mundargi",
            "Sadalagi",
            "Piriyapatna",
            "Adyar"
          ],
          "Manipur": [
            "Imphal",
            "Thoubal",
            "Lilong",
            "Mayang Imphal"
          ],
          "Kerala": [
            "Thiruvananthapuram",
            "Kochi",
            "Kozhikode",
            "Kollam",
            "Thrissur",
            "Palakkad",
            "Alappuzha",
            "Malappuram",
            "Ponnani",
            "Vatakara",
            "Kanhangad",
            "Taliparamba",
            "Koyilandy",
            "Neyyattinkara",
            "Kayamkulam",
            "Nedumangad",
            "Kannur",
            "Tirur",
            "Kottayam",
            "Kasaragod",
            "Kunnamkulam",
            "Ottappalam",
            "Thiruvalla",
            "Thodupuzha",
            "Chalakudy",
            "Changanassery",
            "Punalur",
            "Nilambur",
            "Cherthala",
            "Perinthalmanna",
            "Mattannur",
            "Shoranur",
            "Varkala",
            "Paravoor",
            "Pathanamthitta",
            "Peringathur",
            "Attingal",
            "Kodungallur",
            "Pappinisseri",
            "Chittur-Thathamangalam",
            "Muvattupuzha",
            "Adoor",
            "Mavelikkara",
            "Mavoor",
            "Perumbavoor",
            "Vaikom",
            "Palai",
            "Panniyannur",
            "Guruvayoor",
            "Puthuppally",
            "Panamattom"
          ],
          "Delhi": [
            "Delhi",
            "New Delhi"
          ],
          "DadraandNagarHaveli": [
            "Silvassa"
          ],
          "Puducherry": [
            "Pondicherry",
            "Karaikal",
            "Yanam",
            "Mahe"
          ],
          "Uttarakhand": [
            "Dehradun",
            "Hardwar",
            "Haldwani-cum-Kathgodam",
            "Srinagar",
            "Kashipur",
            "Roorkee",
            "Rudrapur",
            "Rishikesh",
            "Ramnagar",
            "Pithoragarh",
            "Manglaur",
            "Nainital",
            "Mussoorie",
            "Tehri",
            "Pauri",
            "Nagla",
            "Sitarganj",
            "Bageshwar"
          ],
          "UttarPradesh": [
            "Lucknow",
            "Kanpur",
            "Firozabad",
            "Agra",
            "Meerut",
            "Varanasi",
            "Allahabad",
            "Amroha",
            "Moradabad",
            "Aligarh",
            "Saharanpur",
            "Noida",
            "Loni",
            "Jhansi",
            "Shahjahanpur",
            "Rampur",
            "Modinagar",
            "Hapur",
            "Etawah",
            "Sambhal",
            "Orai",
            "Bahraich",
            "Unnao",
            "Rae Bareli",
            "Lakhimpur",
            "Sitapur",
            "Lalitpur",
            "Pilibhit",
            "Chandausi",
            "Hardoi ",
            "Azamgarh",
            "Khair",
            "Sultanpur",
            "Tanda",
            "Nagina",
            "Shamli",
            "Najibabad",
            "Shikohabad",
            "Sikandrabad",
            "Shahabad, Hardoi",
            "Pilkhuwa",
            "Renukoot",
            "Vrindavan",
            "Ujhani",
            "Laharpur",
            "Tilhar",
            "Sahaswan",
            "Rath",
            "Sherkot",
            "Kalpi",
            "Tundla",
            "Sandila",
            "Nanpara",
            "Sardhana",
            "Nehtaur",
            "Seohara",
            "Padrauna",
            "Mathura",
            "Thakurdwara",
            "Nawabganj",
            "Siana",
            "Noorpur",
            "Sikandra Rao",
            "Puranpur",
            "Rudauli",
            "Thana Bhawan",
            "Palia Kalan",
            "Zaidpur",
            "Nautanwa",
            "Zamania",
            "Shikarpur, Bulandshahr",
            "Naugawan Sadat",
            "Fatehpur Sikri",
            "Shahabad, Rampur",
            "Robertsganj",
            "Utraula",
            "Sadabad",
            "Rasra",
            "Lar",
            "Lal Gopalganj Nindaura",
            "Sirsaganj",
            "Pihani",
            "Shamsabad, Agra",
            "Rudrapur",
            "Soron",
            "SUrban Agglomerationr",
            "Samdhan",
            "Sahjanwa",
            "Rampur Maniharan",
            "Sumerpur",
            "Shahganj",
            "Tulsipur",
            "Tirwaganj",
            "PurqUrban Agglomerationzi",
            "Shamsabad, Farrukhabad",
            "Warhapur",
            "Powayan",
            "Sandi",
            "Achhnera",
            "Naraura",
            "Nakur",
            "Sahaspur",
            "Safipur",
            "Reoti",
            "Sikanderpur",
            "Saidpur",
            "Sirsi",
            "Purwa",
            "Parasi",
            "Lalganj",
            "Phulpur",
            "Shishgarh",
            "Sahawar",
            "Samthar",
            "Pukhrayan",
            "Obra",
            "Niwai",
            "Mirzapur"
          ],
          "Bihar": [
            "Patna",
            "Gaya",
            "Bhagalpur",
            "Muzaffarpur",
            "Darbhanga",
            "Arrah",
            "Begusarai",
            "Chhapra",
            "Katihar",
            "Munger",
            "Purnia",
            "Saharsa",
            "Sasaram",
            "Hajipur",
            "Dehri-on-Sone",
            "Bettiah",
            "Motihari",
            "Bagaha",
            "Siwan",
            "Kishanganj",
            "Jamalpur",
            "Buxar",
            "Jehanabad",
            "Aurangabad",
            "Lakhisarai",
            "Nawada",
            "Jamui",
            "Sitamarhi",
            "Araria",
            "Gopalganj",
            "Madhubani",
            "Masaurhi",
            "Samastipur",
            "Mokameh",
            "Supaul",
            "Dumraon",
            "Arwal",
            "Forbesganj",
            "BhabUrban Agglomeration",
            "Narkatiaganj",
            "Naugachhia",
            "Madhepura",
            "Sheikhpura",
            "Sultanganj",
            "Raxaul Bazar",
            "Ramnagar",
            "Mahnar Bazar",
            "Warisaliganj",
            "Revelganj",
            "Rajgir",
            "Sonepur",
            "Sherghati",
            "Sugauli",
            "Makhdumpur",
            "Maner",
            "Rosera",
            "Nokha",
            "Piro",
            "Rafiganj",
            "Marhaura",
            "Mirganj",
            "Lalganj",
            "Murliganj",
            "Motipur",
            "Manihari",
            "Sheohar",
            "Maharajganj",
            "Silao",
            "Barh",
            "Asarganj"
          ],
          "Gujarat": [
            "Ahmedabad",
            "Surat",
            "Vadodara",
            "Rajkot",
            "Bhavnagar",
            "Jamnagar",
            "Nadiad",
            "Porbandar",
            "Anand",
            "Morvi",
            "Mahesana",
            "Bharuch",
            "Vapi",
            "Navsari",
            "Veraval",
            "Bhuj",
            "Godhra",
            "Palanpur",
            "Valsad",
            "Patan",
            "Deesa",
            "Amreli",
            "Anjar",
            "Dhoraji",
            "Khambhat",
            "Mahuva",
            "Keshod",
            "Wadhwan",
            "Ankleshwar",
            "Savarkundla",
            "Kadi",
            "Visnagar",
            "Upleta",
            "Una",
            "Sidhpur",
            "Unjha",
            "Mangrol",
            "Viramgam",
            "Modasa",
            "Palitana",
            "Petlad",
            "Kapadvanj",
            "Sihor",
            "Wankaner",
            "Limbdi",
            "Mandvi",
            "Thangadh",
            "Vyara",
            "Padra",
            "Lunawada",
            "Rajpipla",
            "Vapi",
            "Umreth",
            "Sanand",
            "Rajula",
            "Radhanpur",
            "Mahemdabad",
            "Ranavav",
            "Tharad",
            "Mansa",
            "Umbergaon",
            "Talaja",
            "Vadnagar",
            "Manavadar",
            "Salaya",
            "Vijapur",
            "Pardi",
            "Rapar",
            "Songadh",
            "Lathi",
            "Adalaj",
            "Chhapra",
            "Gandhinagar"
          ],
          "Telangana": [
            "Hyderabad",
            "Warangal",
            "Nizamabad",
            "Karimnagar",
            "Ramagundam",
            "Khammam",
            "Mahbubnagar",
            "Mancherial",
            "Adilabad",
            "Suryapet",
            "Jagtial",
            "Miryalaguda",
            "Nirmal",
            "Kamareddy",
            "Kothagudem",
            "Bodhan",
            "Palwancha",
            "Mandamarri",
            "Koratla",
            "Sircilla",
            "Tandur",
            "Siddipet",
            "Wanaparthy",
            "Kagaznagar",
            "Gadwal",
            "Sangareddy",
            "Bellampalle",
            "Bhongir",
            "Vikarabad",
            "Jangaon",
            "Bhadrachalam",
            "Bhainsa",
            "Farooqnagar",
            "Medak",
            "Narayanpet",
            "Sadasivpet",
            "Yellandu",
            "Manuguru",
            "Kyathampalle",
            "Nagarkurnool"
          ],
          "Meghalaya": [
            "Shillong",
            "Tura",
            "Nongstoin"
          ],
          "HimachalPraddesh": [
            "Manali"
          ],
          "ArunachalPradesh": [
            "Naharlagun",
            "Pasighat"
          ],
          "Maharashtra": [
            "Mumbai",
            "Pune",
            "Nagpur",
            "Thane",
            "Nashik",
            "Kalyan-Dombivali",
            "Vasai-Virar",
            "Solapur",
            "Mira-Bhayandar",
            "Bhiwandi",
            "Amravati",
            "Nanded-Waghala",
            "Sangli",
            "Malegaon",
            "Akola",
            "Latur",
            "Dhule",
            "Ahmednagar",
            "Ichalkaranji",
            "Parbhani",
            "Panvel",
            "Yavatmal",
            "Achalpur",
            "Osmanabad",
            "Nandurbar",
            "Satara",
            "Wardha",
            "Udgir",
            "Aurangabad",
            "Amalner",
            "Akot",
            "Pandharpur",
            "Shrirampur",
            "Parli",
            "Washim",
            "Ambejogai",
            "Manmad",
            "Ratnagiri",
            "Uran Islampur",
            "Pusad",
            "Sangamner",
            "Shirpur-Warwade",
            "Malkapur",
            "Wani",
            "Lonavla",
            "Talegaon Dabhade",
            "Anjangaon",
            "Umred",
            "Palghar",
            "Shegaon",
            "Ozar",
            "Phaltan",
            "Yevla",
            "Shahade",
            "Vita",
            "Umarkhed",
            "Warora",
            "Pachora",
            "Tumsar",
            "Manjlegaon",
            "Sillod",
            "Arvi",
            "Nandura",
            "Vaijapur",
            "Wadgaon Road",
            "Sailu",
            "Murtijapur",
            "Tasgaon",
            "Mehkar",
            "Yawal",
            "Pulgaon",
            "Nilanga",
            "Wai",
            "Umarga",
            "Paithan",
            "Rahuri",
            "Nawapur",
            "Tuljapur",
            "Morshi",
            "Purna",
            "Satana",
            "Pathri",
            "Sinnar",
            "Uchgaon",
            "Uran",
            "Pen",
            "Karjat",
            "Manwath",
            "Partur",
            "Sangole",
            "Mangrulpir",
            "Risod",
            "Shirur",
            "Savner",
            "Sasvad",
            "Pandharkaoda",
            "Talode",
            "Shrigonda",
            "Shirdi",
            "Raver",
            "Mukhed",
            "Rajura",
            "Vadgaon Kasba",
            "Tirora",
            "Mahad",
            "Lonar",
            "Sawantwadi",
            "Pathardi",
            "Pauni",
            "Ramtek",
            "Mul",
            "Soyagaon",
            "Mangalvedhe",
            "Narkhed",
            "Shendurjana",
            "Patur",
            "Mhaswad",
            "Loha",
            "Nandgaon",
            "Warud"
          ],
          "Goa": [
            "Marmagao",
            "Panaji",
            "Margao",
            "Mapusa"
          ],
          "WestBengal": [
            "Kolkata",
            "Siliguri",
            "Asansol",
            "Raghunathganj",
            "Kharagpur",
            "Naihati",
            "English Bazar",
            "Baharampur",
            "Hugli-Chinsurah",
            "Raiganj",
            "Jalpaiguri",
            "Santipur",
            "Balurghat",
            "Medinipur",
            "Habra",
            "Ranaghat",
            "Bankura",
            "Nabadwip",
            "Darjiling",
            "Purulia",
            "Arambagh",
            "Tamluk",
            "AlipurdUrban Agglomerationr",
            "Suri",
            "Jhargram",
            "Gangarampur",
            "Rampurhat",
            "Kalimpong",
            "Sainthia",
            "Taki",
            "Murshidabad",
            "Memari",
            "Paschim Punropara",
            "Tarakeswar",
            "Sonamukhi",
            "PandUrban Agglomeration",
            "Mainaguri",
            "Malda",
            "Panchla",
            "Raghunathpur",
            "Mathabhanga",
            "Monoharpur",
            "Srirampore",
            "Adra"
          ]
        }
    """.trimIndent()